// /src/app/layout.tsx

import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';
import { TopNav } from '~/app/_components/TopNav';
import { MediaPopupProvider } from './_contexts/MediaPopupContext';
import { AuthProvider } from './_contexts/AuthContext';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const session = await auth();
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex min-h-screen flex-col bg-gray-900 text-gray-400">
        <TRPCReactProvider>
          <AuthProvider>
            <MediaPopupProvider>
              <TopNav /> {/* ✨ Add the navigation bar here */}
              <main className="max-w-7xl mx-auto w-full flex-grow py-4">
                {children}
              </main>
            </MediaPopupProvider>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

// let vercel cron call vps api
// add discord login
// add logo, tab image, etc.
// update watch page visuals
// link to google analytics
// change user submit times to utc

// create a single cron procedure and test

// make media buttons display info according to the search filters (horizontal strips including or not including media description)
// also should media buttons display availability, total episodes, missing episodes?

// use run time (only present in mv details) instead of updatedDate for mv

// if media title isn't english -> don't add to db
// update trpc procedure to update popularity, rating, vote count when fetching new media via tmdb api
// allow user to request new media

// for overview, add "show/hide backdrop" arrow.
// allow 3 modes for season/episode selector: horizontal scrolling, grid, detailed vertical scrolling (show poster, title, description)

// search bar, mv/tv, genre, origin, release year,
// airing status (finished: all episodes are older than yesterday, airing: at least 1 episode is in future, not released: releaseDate in the future),
// availability (full: all episodes have source, partial: at least 1 episode have no src, none: 0 episodes or no episode have src)

// add sorting to the search page (based on title, release date, etc.)
// sorting based on popularity and vote might require adding popularity/voteAverage/voteCount columns to media table
// and require fetching details for all media daily to update those new columns

// login (if you want google oauth for 37.60.250.227 you need a domain for that)
// media request function for users
// way to stop an trpc procedure (eg src fetch) without shutting down the server

// add display modes to search page (grid, detailed grid, horizontal strips)
// add vidfast
// add recapture/cloudflare at access/login

// if a movie belongs to a collection, fetch all others in the collection (and display them as related?)
// add recommendations (just implement your own, tmdb recommendations are too random)
// add login: add admin, add favorite button, add watch later button
// add comment function
// add rating for each mv/tv (make it influence the top rated lists)

// add voting function: vip can name show/mv, then users can vote. top 10 will be added.
// allow commenting on the votes

// player page: add report function (if theres no src) so that i can manually get m3u8 and insert to db
// fix the player to the top while i scroll down
