import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-gray-900 text-gray-400">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}

// popup and player page: add genres
// add dark mode button
// remove watch now button from mv/tv with no src/episode
// season/episode section: add season posters/descriptions, create dropdown for episodes, add no src marker and make srcless episodes unclickable
// player page: add episode description, add media poster/backdrop (need to add backdrop of all media to db), add recommendations (how to implement?)
