import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-gray-900 text-gray-400">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}

// for overview, add "show/hide backdrop" arrow.
// allow 3 modes for season/episode selector: horizontal scrolling, grid, detailed vertical scrolling (show poster, title, description)

// search and filters should be together and present in all pages

// add filters to full list pages (and also home page)
// add recommendations (just implement your own, tmdb recommendations are too random)
// if a movie belongs to a collection, fetch all others in the collection
// add search function
// add filter function
// add login: add admin, add favorite button, add watch later button
// add comment function
// add voting function: vip can name show/mv, then users can vote. top 10 will be added.
// allow commenting on the votes
// add rating for each mv/tv (make it influence the top rated lists)

// player page: add report function (if theres no src) so that i can manually get m3u8 and insert to db
// fix the player to the top while i scroll down
